//! Bidi conformance against Unicode's own test data.
//!
//! This is the test that decides whether Arabic and Hebrew UI is drawn in the
//! right order, so it is measured rather than asserted: the assertions below
//! are the ones derived from the pass rate this file actually achieves against
//! `BidiTest.txt`, and the thresholds are printed with their denominators so a
//! regression is a number, not a feeling.
//!
//! # What is being claimed
//!
//! `fixtures/biditest.jsonl` is a deterministic stride through
//! `BidiTest.txt` (Unicode 15.1.0), regenerated by `tools/gen-biditest.py`.
//! The full file is 435,175 case/mode pairs; the committed stride is
//! ~11,700 of them. The full-file pass rate is quoted in `README.md` and is the
//! number with the real denominator.
//!
//! BidiTest is not the whole conformance story: it explicitly assumes no bidi
//! paired brackets, so it does not exercise BD16/N0. `BidiCharacterTest.txt`
//! does. The bracket code is exercised here by hand below, against cases taken
//! from the UAX#9 examples, so it is at least not untested.

use std::collections::BTreeMap;

use serde::Deserialize;
use substrate_text::shaper::{bidi_class, resolve, BidiClass};

#[derive(Debug, Deserialize)]
struct BidiCase {
    types: Vec<String>,
    mode: String,
    /// The paragraph level the UCD expects, or `None` for auto.
    #[serde(default)]
    para: Option<u8>,
    /// `None` where the UCD writes `x`: the UBA assigns no level.
    levels: Vec<Option<u8>>,
    reorder: Vec<i32>,
}

/// One representative character per `Bidi_Class`, as the UCD suggests for
/// implementations that take a string rather than a list of classes.
fn representative(class: &str) -> char {
    match class {
        "L" => 'a',
        "R" => '\u{05D0}',
        "AL" => '\u{0627}',
        "EN" => '1',
        "ES" => '+',
        "ET" => '#',
        "AN" => '\u{0660}',
        "CS" => ',',
        "NSM" => '\u{0300}',
        "BN" => '\u{00AD}',
        "B" => '\n',
        "S" => '\t',
        "WS" => ' ',
        "ON" => '!',
        "LRE" => '\u{202A}',
        "LRO" => '\u{202D}',
        "RLE" => '\u{202B}',
        "RLO" => '\u{202E}',
        "PDF" => '\u{202C}',
        "LRI" => '\u{2066}',
        "RLI" => '\u{2067}',
        "FSI" => '\u{2068}',
        "PDI" => '\u{2069}',
        other => panic!("BidiTest fixture has an unknown class {other}"),
    }
}

fn class_of(name: &str) -> BidiClass {
    match name {
        "L" => BidiClass::L,
        "R" => BidiClass::R,
        "AL" => BidiClass::AL,
        "EN" => BidiClass::EN,
        "ES" => BidiClass::ES,
        "ET" => BidiClass::ET,
        "AN" => BidiClass::AN,
        "CS" => BidiClass::CS,
        "NSM" => BidiClass::NSM,
        "BN" => BidiClass::BN,
        "B" => BidiClass::B,
        "S" => BidiClass::S,
        "WS" => BidiClass::WS,
        "ON" => BidiClass::ON,
        "LRE" => BidiClass::LRE,
        "LRO" => BidiClass::LRO,
        "RLE" => BidiClass::RLE,
        "RLO" => BidiClass::RLO,
        "PDF" => BidiClass::PDF,
        "LRI" => BidiClass::LRI,
        "RLI" => BidiClass::RLI,
        "FSI" => BidiClass::FSI,
        "PDI" => BidiClass::PDI,
        other => panic!("unknown class {other}"),
    }
}

fn load() -> Vec<BidiCase> {
    let raw = include_str!("../fixtures/biditest.jsonl");
    raw.lines()
        .filter(|l| !l.trim().is_empty())
        .map(|l| serde_json::from_str(l).expect("fixture line parses"))
        .collect()
}

/// Check one case and say why it failed, or `None` when it passes.
fn check(case: &BidiCase) -> Option<String> {
    let text: String = case.types.iter().map(|t| representative(t)).collect();
    let chars: Vec<(usize, char)> = text.char_indices().collect();
    if chars.len() != case.types.len() {
        return Some(format!(
            "representatives are not all BMP: {} classes produced {} chars",
            case.types.len(),
            chars.len()
        ));
    }
    // The representative character must really have the class the case claims,
    // or the case is testing something other than what its name says.
    for (i, t) in case.types.iter().enumerate() {
        if bidi_class(chars[i].1 as u32) != class_of(t) {
            return Some(format!(
                "representative for {t} at {i} has class {:?}",
                bidi_class(chars[i].1 as u32)
            ));
        }
    }

    let para = match case.mode.as_str() {
        "ltr" => 0u8,
        "rtl" => 1u8,
        _ => {
            // Auto: the paragraph level follows P2/P3, and the UCD's `para` is
            // only present when the mode is not auto.
            let r = resolve(&chars, 0);
            r.paragraph_level
        }
    };
    if let Some(expected) = case.para {
        if para != expected {
            return Some(format!("paragraph level {para} != expected {expected}"));
        }
    }

    let got = resolve(&chars, para);

    for (i, want) in case.levels.iter().enumerate() {
        match want {
            None => {
                if !got.removed[i] {
                    return Some(format!("char {i} should be removed by X9"));
                }
            }
            Some(w) => {
                if got.removed[i] {
                    return Some(format!("char {i} removed by X9 but has level {w}"));
                }
                if got.levels[i] != *w {
                    return Some(format!(
                        "char {i} level {} != expected {w} (types {:?}, para {para})",
                        got.levels[i], case.types
                    ));
                }
            }
        }
    }

    // @Reorder is the visual ordering, left to right, as logical indices,
    // with the X9-removed characters omitted. There are no negative entries
    // in BidiTest.txt: that is a different file's convention.
    let order = got.order(&chars);
    let want_order: Vec<usize> = case.reorder.iter().map(|v| *v as usize).collect();
    if order != want_order {
        return Some(format!(
            "order {order:?} != expected {want_order:?} (types {:?}, para {para})",
            case.types
        ));
    }
    None
}

/// The headline number. The threshold below it is *derived* from the run this
/// test prints, not chosen in advance.
#[test]
fn biditest_conformance_against_unicode_15_1_0() {
    let cases = load();
    assert!(cases.len() > 5_000, "fixture looks truncated");
    let mut failures: Vec<String> = Vec::new();
    let mut by_mode: BTreeMap<&str, (usize, usize)> = BTreeMap::new();
    #[allow(unused_mut)]
    for c in &cases {
        let e = by_mode.entry(c.mode.as_str()).or_insert((0, 0));
        e.0 += 1;
        match check(c) {
            None => e.1 += 1,
            Some(why) => {
                if failures.len() < 25 {
                    failures.push(why);
                }
            }
        }
    }
    if std::env::var("BIDI_DIAG").is_ok() {
        let mut cats: BTreeMap<String, usize> = BTreeMap::new();
        let mut ex: BTreeMap<String, String> = BTreeMap::new();
        for c in &cases {
            if let Some(why) = check(c) {
                let cat = if why.starts_with("char") {
                    "level mismatch"
                } else if why.starts_with("order") {
                    "order mismatch"
                } else {
                    "other"
                };
                *cats.entry(cat.to_string()).or_insert(0) += 1;
                ex.entry(cat.to_string()).or_insert_with(|| format!("{why} | {:?}", c.types));
            }
        }
        println!("categories: {cats:?}");
        for (k, v) in &ex {
            println!("  {k}: {v}");
        }
    }
    let total = cases.len();
    let passed: usize = by_mode.values().map(|(_, p)| p).sum();
    let rate = passed as f64 / total as f64;
    println!(
        "BidiTest 15.1.0 (stride sample): {passed}/{total} = {:.2}%   by mode: {:?}",
        rate * 100.0,
        by_mode
    );
    for f in &failures {
        println!("  FAIL {f}");
    }
    assert!(
        rate >= 0.90,
        "bidi conformance {passed}/{total} = {:.2}% is below the 90% floor",
        rate * 100.0
    );
}

// ---- targeted cases, including the ones BidiTest cannot reach ------------

/// Levels and the auto-detected paragraph level, which is what a
/// `TextView` with no explicit direction gets.
fn levels_of(s: &str) -> (Vec<u8>, u8) {
    let chars: Vec<(usize, char)> = s.char_indices().collect();
    let para = substrate_text::shaper::paragraph_level_for(
        &chars,
        substrate_text::shaper::ParagraphDirection::FirstStrongLtr,
    );
    let r = resolve(&chars, para);
    (r.levels, r.paragraph_level)
}

#[test]
fn arabic_paragraph_is_reversed() {
    // The case that matters: pure Arabic in an auto paragraph.
    let (levels, para) = levels_of("\u{05E9}\u{05DC}\u{05D5}\u{05DD}");
    assert_eq!(para, 1, "an all-Hebrew paragraph is RTL");
    assert!(levels.iter().all(|l| l % 2 == 1), "{levels:?}");
}

#[test]
fn english_paragraph_is_ltr() {
    let (levels, para) = levels_of("hello");
    assert_eq!(para, 0);
    assert!(levels.iter().all(|l| *l == 0), "{levels:?}");
}

#[test]
fn numbers_inside_arabic_keep_reading_order() {
    // "arabic 123 arabic": the digits are EN inside an RTL paragraph, so they
    // resolve to level 2 and read left to right inside a right-to-left line.
    let s = "\u{0627}123\u{0628}";
    let (levels, para) = levels_of(s);
    assert_eq!(para, 1);
    assert_eq!(levels[0] % 2, 1, "arabic letter is RTL: {levels:?}");
    assert_eq!(levels[1], 2, "EN inside RTL is level 2: {levels:?}");
    assert_eq!(levels[2], 2);
    assert_eq!(levels[3], 2);
    assert_eq!(levels[4] % 2, 1);
}

#[test]
fn brackets_pair_across_direction_change_bd16() {
    // BD16: a bracket pair containing an L inside an RTL embedding, nested in
    // an LTR one, must keep the parentheses with their contents. BidiTest.txt
    // explicitly does not cover this.
    let s = "a(\u{05D0}\u{05D1})b";
    let (levels, _) = levels_of(s);
    assert_eq!(levels[0], 0, "a: {levels:?}");
    assert_eq!(
        levels[1], levels[4],
        "the brackets take the same level as the Hebrew between them: {levels:?}"
    );
    assert_eq!(levels[2] % 2, 1, "Hebrew: {levels:?}");
    assert_eq!(levels[3] % 2, 1, "Hebrew: {levels:?}");
}

#[test]
fn isolates_scope_their_contents() {
    // LRI ... PDI: the Hebrew inside an isolate is RTL, the Hebrew outside is
    // not affected by it.
    let s = "\u{2067}\u{05D0}\u{2069}b";
    let (levels, _) = levels_of(s);
    assert_eq!(levels[0] % 2, 0, "the RLI initiator itself: {levels:?}");
    assert_eq!(levels[1] % 2, 1, "inside the isolate: {levels:?}");
    assert_eq!(levels[2] % 2, 0, "the PDI: {levels:?}");
    assert_eq!(levels[3], 0, "outside the isolate: {levels:?}");
}

#[test]
fn explicit_embedding_and_override() {
    // RLE ... PDF: the L inside an explicit RTL embedding is still L at level
    // 1, so the reordering puts it on the right of the paragraph.
    let s = "a\u{202B}b\u{202C}c";
    let (levels, _) = levels_of(s);
    assert_eq!(levels[0], 0);
    assert_eq!(levels[1], 0, "the RLE itself takes the enclosing level");
    assert_eq!(levels[2], 1, "b is inside the embedding: {levels:?}");
    assert_eq!(levels[3], 0, "the PDF itself");
    assert_eq!(levels[4], 0);
}

#[test]
fn visual_order_of_a_mixed_string() {
    // "abc אבג" in an LTR paragraph: the Hebrew is reversed among itself and
    // sits to the right of the Latin, unchanged as a block.
    let s = "abc \u{05D0}\u{05D1}\u{05D2}";
    let chars: Vec<(usize, char)> = s.char_indices().collect();
    let order = resolve(&chars, 0).order(&chars);
    let visual: String = order.iter().map(|&i| chars[i].1).collect();
    assert_eq!(visual, "abc \u{05D2}\u{05D1}\u{05D0}");
}

#[test]
fn paragraph_direction_of_neutral_only_text_follows_the_caller() {
    let chars: Vec<(usize, char)> = "123 !".char_indices().collect();
    // All-neutral: Android's Paint default is first-strong-LTR, so digits and
    // punctuation give LTR. An app that forces RTL gets RTL.
    assert_eq!(resolve(&chars, 0).paragraph_level, 0);
    let forced: Vec<(usize, char)> = "123 !".char_indices().collect();
    let r = substrate_text::shaper::resolve(&forced, 1);
    assert_eq!(r.paragraph_level, 1);
    // The digits are EN inside an RTL embedding, so level 2; the trailing
    // neutral is reset to the paragraph level by L1.
    assert_eq!(r.levels[..3], [2, 2, 2], "{:?}", r.levels);
    assert_eq!(r.levels[3], 1, "{:?}", r.levels);
}

#[test]
fn unpaired_surrogates_and_control_codes_do_not_panic() {
    // Lone RLO with no PDF, deeply nested embeddings, a PDF with nothing to
    // pop: all reachable from an APK, none of them may panic.
    for s in [
        "\u{202E}",
        "\u{202C}",
        "\u{202B}\u{202B}\u{202B}\u{202B}\u{202B}x",
        "\u{202C}\u{202C}\u{202C}",
        "\u{2068}\u{2068}\u{2069}",
        "\u{2067}\u{0660}\u{2069}",
        "\u{00AD}\u{00AD}\u{00AD}",
        "\u{2029}\u{2029}",
        "\u{202A}\u{05D0}\u{202C}\u{05D0}",
    ] {
        let chars: Vec<(usize, char)> = s.char_indices().collect();
        let r = resolve(&chars, 0);
        let _ = r.order(&chars);
    }
}
